#!/usr/bin/python3
import argparse
import usb.core
def main():
    parser = argparse.ArgumentParser(description='Change Luxafor color')
    color_codes = {
            'red'    : (255, 0, 0),
            'green'  : (0, 255, 0),
            'blue'   : (0, 0, 255),
            'yellow' : (255, 255, 0),
            'magenta': (255, 0, 255),
            'cyan'   : (0, 255, 255),
            'orange' : (255, 128, 0),
            'pink'   : (255, 0, 128),
            'purple' : (128, 0, 255),
            'lime'   : (128, 255, 0),
            'white'  : (255, 255, 255),
            'off'    : (0, 0, 0), }
    parser.add_argument('color', choices=color_codes.keys(), help='color to change to')
    args = parser.parse_args()
    dev = usb.core.find(idVendor=0x04d8, idProduct=0xf372)
    if dev is None:
            print('Not connected')
            return
    try:
        dev.detach_kernel_driver(0)
    except usb.core.USBError:
        pass
    try:
        dev.set_configuration()
    except usb.core.USBError:
        print("Did you give Luxafor USB permission to your user?")
        return
    dev.set_configuration()
    dev.write(1, [0, 0])
    dev.write(1, [1, 255, *color_codes[args.color]])
if __name__ == '__main__':
    main()
